# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Native Libraries

on:
    push:
        branches:
            - '*'
        tags:
            - '[0-9]*'
        paths:
            - 'flatlaf-natives/**'
            - '.github/workflows/natives.yml'
            - 'gradle/wrapper/gradle-wrapper.properties'
            - '!**.md'
            - '!**/.settings/**'

jobs:
    Natives:
        strategy:
            matrix:
                os:
                    - windows
                    - macos
                    - ubuntu

        runs-on: ${{ matrix.os }}-latest

        steps:
            - uses: actions/checkout@v4

            - uses: gradle/wrapper-validation-action@v2

            - name: Setup Java 11
              uses: actions/setup-java@v4
              with:
                  java-version: 11
                  distribution: temurin

            - name: Build with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                gradle-version: wrapper
                arguments: build-natives

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: FlatLaf-natives-build-artifacts-${{ matrix.os }}
                  path: |
                      flatlaf-core/src/main/resources/com/formdev/flatlaf/natives
                      flatlaf-natives/flatlaf-natives-*/build
